name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies (./src)
      run: dotnet restore ./src
    - name: Install dependencies (./tests)
      run: dotnet restore ./tests
    - name: Build (./src)
      run: dotnet build ./src --configuration Release --no-restore
    - name: Test (./tests)
      run: dotnet test ./tests --no-restore --verbosity normal
